listen = ":7109"
releaseMode = true

[token]
tokenLibVersion = 1
AccessTokenTTL = "2h"
RefreshTokenTTL = "168h"
AccessTokenExpireSoon = "0m"
PrivateKeyPath = "./conf/ecdsa_prv.pem"
PublicKeyPath = "./conf/ecdsa_pub.pem"

[sms]
addr = "127.0.0.1:7104"

[monitor]
namespace = "umbrella"
subsystem = "user"

[verify]
defaultLength = 6
maxSendTimes = 5
maxCheckTimes = 5
ttl = "15m"

[captcha]
defaultLength = 5
defaultWidth = 240
defaultHeight = 80
ttl = "86400s"

[login]
ttl = "10m"
maxRequestTimes = 5
maxCaptchaTImes = 1
cleanInvalidTokenThreshold = 1000
maxNumberLogin = 2000

[mysql]
dsn = "root:root@tcp(127.0.0.1:3306)/umbrella?charset=utf8mb4,utf8&parseTime=True&loc=UTC"
maxIdle = 1
maxOpen = 2

[redis]
addr = "127.0.0.1:6379"
password = ""
poolSize = 5
db = 2
timeout = "3s"

[http]
listen = ":7108"
